### ISSUE TITLE
uiux: 讓首頁更有正在進行挑戰的感覺

### ISSUE THREAD

**Issue by antoncoding** [AlibudaLab/nouns-habit-builder#171]
提議：
1. 用圓形的 progress bar 或是別的形式讓我們的 checkin count 看起來不只是呆呆的數字
e.g.

2. 我在重複登入時，最想看到的資訊是挑戰剩下幾天 還有裡面各有多少錢

**Comment by antoncoding** [comment]
example

<img width="397" alt="Screenshot 2024-08-29 at 00 35 30" src="https://github.com/user-attachments/assets/5e9c6bba-5d5e-461f-a3e7-56459844385b">

**Comment by antoncoding** [comment]
## With money staked
<img width="388" alt="Screenshot 2024-08-29 at 00 37 36" src="https://github.com/user-attachments/assets/0ff0d61f-42fa-4e5c-a7ba-23b4ab5b1cd6">

**Comment by Ankarrr** [comment]
good idea!!

**Comment by cc03668** [comment]
![Image](https://github.com/user-attachments/assets/8ed823df-7cb3-4cd2-8c6b-3e4cad7bea9e)



![Image](https://github.com/user-attachments/assets/cb7383f8-24f9-4274-8f8e-cebd2ec56fb6)
