### ISSUE TITLE
uiux: checkin 不明顯

### ISSUE THREAD

**Issue by antoncoding** [AlibudaLab/nouns-habit-builder#172]
* Feedback from user: check in 不夠明顯
* 我覺得可能的解決方法：這頁太多資訊，例如 check in instruction，看玩一次之後就不需要了，應該用 tooltip 處理，而不是佔版面
* money staked 相同，佔太多空間

<img width="415" alt="Screenshot 2024-08-29 at 00 39 32" src="https://github.com/user-attachments/assets/a4d2ba40-1b2e-4cd9-ae8d-411e9c0cd38e">
<img width="384" alt="Screenshot 2024-08-29 at 00 40 12" src="https://github.com/user-attachments/assets/64d93af2-d451-470a-b3b3-431e1878d5bd">

**Comment by Ankarrr** [comment]
同意 check in 很不明顯，需要解決！

**Comment by cc03668** [comment]
![Image](https://github.com/user-attachments/assets/b372d664-55ed-4c70-a3ff-91619f81d405)
